FROM ubuntu:18.04
MAINTAINER fuyao@bu.edu

RUN apt-get -y update
RUN apt-get install -y sudo vim git wget 
RUN sudo apt install -y build-essential cmake libgmp3-dev libcppunit-dev libpthread-stubs0-dev


RUN cd /root/